dataSource:
  pooled: true
  jmxExport: true
  driverClassName: org.postgresql.Driver
  dialect: org.hibernate.dialect.PostgreSQLDialect
  username: rafa
  password: rafa5555

environments:
  development:
    dataSource:
      dbCreate: update
      url: jdbc:postgresql://localhost:5432/testdb
  test:
    dataSource:
      dbCreate: update
      url: jdbc:postgresql://localhost:5432/testdb
  production:
    dataSource:
      dbCreate: update
      url: jdbc:postgresql://localhost:5432/testdb
      properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
